# <center>M1 T01: Programación Numérica

In [1]:
# Siento no seguir el estándar de importar numpy como "np", pero creo que vale la pena escribir tres letras de más
#   (a cambio de que el código se entienda mejor):

import numpy

## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
def get_array_info(input_array):
    if input_array.ndim > 1:
        print("ERROR: El Array no puede tener más de una Dimensión.")
    else:
        print(f"Cantidad de elementos del array: {input_array.shape[0]}")
        print(f"Tipo de Datos de los elementos: {input_array.dtype}")
        print(f"Valor Mínimo: {input_array.min()}")
        print(f"Valor Máximo: {input_array.max()}")
        print(f"Valor Promedio: {input_array.mean()}")
        print(f"Desviación Estándar: {input_array.std()}")
        print(f"Suma de los Valores: {input_array.sum()}")

In [3]:
my_array_1D = numpy.array([1, 2, 3, 4, 5]) 
get_array_info(my_array_1D)

Cantidad de elementos del array: 5
Tipo de Datos de los elementos: int32
Valor Mínimo: 1
Valor Máximo: 5
Valor Promedio: 3.0
Desviación Estándar: 1.4142135623730951
Suma de los Valores: 15


In [4]:
my_array_3D = numpy.array([[[1, 2, 3], [4, 5, 6]] , [[1, 2, 3], [4, 5, 6]]])
get_array_info(my_array_3D)

ERROR: El Array no puede tener más de una Dimensión.


## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [5]:
def get_random_array(regs, values):
    if type(regs) != int or type(values) != int:
        print("ERROR: Los parámetros de la función deben ser números enteros.")
    else:
        return numpy.random.randint(100, size=(regs, values))

In [6]:
get_random_array(3, 5)

array([[10, 46,  4, 14, 97],
       [83, 96, 45, 22, 74],
       [92, 60, 23, 38,  0]])

In [7]:
get_random_array(3.5, 5)

ERROR: Los parámetros de la función deben ser números enteros.


In [8]:
get_random_array('hola', 5)

ERROR: Los parámetros de la función deben ser números enteros.


## Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [9]:
my_array_2D = numpy.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

print(my_array_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
def array_sum(input_array):
    if input_array.ndim != 2:
        print("ERROR: El Array debe tener 2 Dimensiones.")
    else:
        # Variables para almacenar los índices:
        row_index = 0
        col_index = 0
        # Arrays con las sumas de las filas y las columnas:
        row_sum = input_array.sum(axis=1)
        col_sum = input_array.sum(axis=0)
        # Itero el array de suma de filas, para imprimir los valores:
        for value in row_sum:
            print(f"Total Fila {row_index}: {value}")
            row_index += 1
        # Itero el array de suma de columnas, para imprimir los valores:
        for value in col_sum:
            print(f"Total Columna {col_index}: {value}")
            col_index += 1

In [11]:
array_sum(my_array_2D)

Total Fila 0: 6
Total Fila 1: 15
Total Fila 2: 24
Total Columna 0: 12
Total Columna 1: 15
Total Columna 2: 18


In [12]:
array_sum(my_array_1D)

ERROR: El Array debe tener 2 Dimensiones.


## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [13]:
def get_corr_manual(array1, array2):
    # Calculo la covarianza:
    cov = (sum(numpy.prod([array1, array2], axis=0)) / len(array1)) - (array1.mean() * array2.mean())
    # Calculo la correlación:
    corr = cov / (array1.std() * array2.std())
    # Imprimo el resultado, con 3 decimales:
    print(round(corr, 3))

In [14]:
array1 = numpy.array([1,5,9,10,12])
array2 = numpy.array([4,6,7,8,9])

In [15]:
get_corr_manual(array1, array2)

0.988


In [16]:
# Se puede calcular más fácil con la función "corrcoef" de numpy:

def get_corr_auto(array1, array2):
    # Calculo la correlación:
    corr = numpy.corrcoef(array1, array2)[0, 1]
    # Imprimo el resultado, con 3 decimales:
    print(round(corr, 3))

In [17]:
get_corr_auto(array1, array2)

0.988


---